USE [master]
GO

CREATE LOGIN [adminR-Ticket] WITH PASSWORD='admin', DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[русский], CHECK_EXPIRATION=OFF, CHECK_POLICY=ON
GO

ALTER LOGIN [adminR-Ticket] DISABLE
GO

ALTER SERVER ROLE [dbcreator] ADD MEMBER [adminR-Ticket]
GO

CREATE LOGIN [defaultR-Ticket] WITH PASSWORD='default', DEFAULT_DATABASE=[R-Ticket], DEFAULT_LANGUAGE=[русский], CHECK_EXPIRATION=OFF, CHECK_POLICY=ON
GO

ALTER LOGIN [defaultR-Ticket] DISABLE
GO

CREATE LOGIN [dispatcherR-Ticket] WITH PASSWORD='dispatcher', DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[русский], CHECK_EXPIRATION=OFF, CHECK_POLICY=ON
GO

ALTER LOGIN [dispatcherR-Ticket] DISABLE
GO

CREATE LOGIN [userR-Ticket] WITH PASSWORD='user', DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[русский], CHECK_EXPIRATION=OFF, CHECK_POLICY=ON
GO

ALTER LOGIN [userR-Ticket] DISABLE
GO